StartupEvents.registry('item', event => {
  event.create('item.enriched_prismarine').texture('kubejs:item/enriched_prismarine').displayName('Enriched Prismarine')
  event.create('item.picochip_processor').texture('kubejs:item/animated/picochip_processor').displayName('Picochip Processor')
  event.create('item.pico_processor').texture('kubejs:item/pico_processor').displayName('Picoprocessor')
  event.create('item.pico_processor_assembly').texture('kubejs:item/pico_processor_assembly').displayName('Picoprocessor Assembly')
  event.create('item.pico_processor_computer').texture('kubejs:item/pico_processor_computer').displayName('Picoprocessor Supercomputer')
  event.create('item.pico_processor_mainframe').texture('kubejs:item/animated/pico_processor_mainframe').displayName('Picoprocessor Mainframe')
  event.create('item.fission_upgrade').texture('kubejs:item/fission_upgrade').displayName('Fission Upgrade Kit')
  event.create('incomplete_control_rod_assembly').displayName('Incomplete Control Rod Assembly')
  event.create('item.high_grade_sand').texture('kubejs:item/high_grade_sand').displayName('High Grade Sand')
  event.create('instakill', 'sword').tier('instakill').texture('kubejs:item/damage').displayName('Instant Death')
  event.create('incomplete')
  event.create('pellet_mold')
  event.create('sodium_pellet')
  event.create('reinforced_rocket_fin').texture('kubejs:item/rocket_fin_2').displayName('Reinforced Rocket Fin')
  event.create('reinforced_rocket_nose_cone').texture('kubejs:item/rocket_nose_cone_2').displayName('Reinforced Rocket Nose Cone')
  event.create('steel_fibers').texture('kubejs:item/steel_fibers').displayName('Steel Fibers')
  event.create('layered_steel_threads').texture('kubejs:item/layered_steel').displayName('Layered Steel Threads')
  event.create('rough_damascus_steel_ingot').texture('kubejs:item/rough_damascus').displayName('Rough Damascus Steel Ingot')
})
