GTCEuServerEvents.fluidVeins(event => {
  event.add('novafactory:moon_desh_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:moon')
    vein.fluid(() => Fluid.of('gtceu:moon_desh_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:mars_desh_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:mars')
    vein.fluid(() => Fluid.of('gtceu:mars_desh_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:venus_desh_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:venus')
    vein.fluid(() => Fluid.of('gtceu:venus_desh_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:mercury_desh_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:mercury')
    vein.fluid(() => Fluid.of('gtceu:mercury_desh_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:mars_ostrum_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:mars')
    vein.fluid(() => Fluid.of('gtceu:mars_ostrum_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:mercury_ostrum_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:mercury')
    vein.fluid(() => Fluid.of('gtceu:mercury_ostrum_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:venus_ostrum_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:venus')
    vein.fluid(() => Fluid.of('gtceu:venus_ostrum_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
  event.add('novafactory:calorite_rich_magma_deposit', vein => {
    vein.dimensions('ad_astra:venus')
    vein.fluid(() => Fluid.of('gtceu:venus_calorite_rich_magma').fluid)
    vein.weight(600)
    vein.minimumYield(120)
    vein.maximumYield(720)
    vein.depletionAmount(2)
    vein.depletionChance(1)
    vein.depletedYield(5)
  })
})
